version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLAG=FLAG{pr0t0typ3_p0llut10n_ch41n_3x4mpl3}
      - NODE_ENV=production
    restart: unless-stopped
    # リソース制限（DoS防止）
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    # セキュリティ設定
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
